[build]
  command = "npm run build"
  functions = "../server/netlify/functions" # Tells Netlify where the functions are located
  publish = "../client/dist" # Tells Netlify where the static React files are located

[build.environment]
  NODE_VERSION = "20"
  NPM_FLAGS = "--prefix client"