[build]
  command = "npm run build"
  functions = "netlify/functions" # Tells Netlify where the functions are located
  publish = "client/dist" # Tells Netlify where the static React files are located